### ISSUE TITLE
service-name vs. service-dns issue

### ISSUE THREAD

**Issue by amoAHCP** [hazelcast/hazelcast-operator#50]
Hi, using the enterprise operator I got a confusing situation regarding the discovery strategy. According to https://github.com/hazelcast/hazelcast-kubernetes service-dns is a valid way for discovery. If you add this (example below), the operator adds automatically a service-name and the deployment fails because now service-name and service-dns is present at the same time!

apiVersion: hazelcast.com/v1alpha1
kind: HazelcastEnterprise
metadata:
  name: my-cluster
spec:
  cluster:
    memberCount: 3

  mancenter:
    # ingress configuration for mancenter
    ingress:
      enabled: true
    persistence:
      size: 1Gi

  hazelcast:
    licenseKeySecretName: hz-license-key-secret

    hot-restart-persistence:
      enabled: ${hazelcast.hotRestart}
      base-dir: /data/hot-restart
      validation-timeout-seconds: 1200
      data-load-timeout-seconds: 900
      auto-remove-stale-data: true
    management-center:
      enabled: ${hazelcast.mancenter.enabled}
      url: ${hazelcast.mancenter.url}

    yaml:
      hazelcast:
        serialization:
          allow-override-default-serializers: true
        client:
          statistics:
            enabled: true
        enabled: true
        cluster-name: my-cluster
        native-memory:
          enabled: true
          allocator-type: STANDARD
          size:
            unit: GIGABYTES
            value: 2
          min-block-size: 128
          page-size: 123
          metadata-space-percentage: 12.5
        network:
          join:
            multicast:
              enabled: false
            kubernetes:
              enabled: true
              service-dns: ${serviceName}.${namespace}.svc.cluster.local
              resolve-not-ready-addresses: true

**Comment by leszko** [comment]
Please check the following part: https://github.com/hazelcast/charts/tree/master/stable/hazelcast#using-dns-lookup-discovery

You need to set empty strings to `service-name`.

**Comment by amoAHCP** [comment]
@leszko ahh... ok, strange solution but OK
